# Generated by Django 5.1.11 on 2025-09-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='positions',
            field=models.IntegerField(default=1),
        ),
    ]
